import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Learn Next.js',
  description: 'Project for learning Next.js with Kodaps tutorial.Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
