import './globals.css'

export const metadata = {
  title: 'Learn Next.js',
  description: 'Project for learning Next.js with Kodaps tutorial.Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
